config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  devise_for :users

  resources :cell_goal_tasks
  resources :cell_goals
  resources :board_goal_tasks
  # resources :board_goals
  resources :projects
  resources :cell_tasks
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :boards
  resources :cells
    


  # Tarefas de uma Diretoria
  get '/boards/:board_id/tasks/new', to: 'board_tasks#new', as: 'new_board_task'
  post '/boards/:board_id/tasks', to: 'board_tasks#create', as: 'board_tasks'
  get '/boards/:board_id/tasks/:task_id', to: 'board_tasks#show', as: 'board_task'
  patch '/boards/:board_id/tasks/:task_id', to: 'board_tasks#update'
  get '/boards/:board_id/tasks/:task_id/edit', to: 'board_tasks#edit', as: 'edit_board_task'

  # Metas de uma diretoria
  get '/boards/:board_id/goals/new', to: 'board_goals#new', as: 'new_board_goal'
  post '/boards/:board_id/goals', to: 'board_goals#create', as: 'board_goals'
  get '/boards/:board_id/goals/:goal_id', to: 'board_goals#show', as: 'board_goal'
  get '/boards/:board_id/goals/:goal_id/edit', to: 'board_goals#edit', as: 'edit_board_goal'
  patch '/boards/:board_id/goals/:goal_id', to: 'board_goals#update'

  namespace :forum do
    get '/', to: 'posts#index'
    get '/postagens', to: 'posts#index', as: 'posts'
    get '/postagens/novo', to: 'posts#new', as: 'new_post'
    post '/postagens', to: 'posts#create'

    get '/postagens/:id', to: 'posts#show', as: 'post'

    delete '/postagens/:id', to: 'posts#destroy'

    post '/postagens/:post_id/like', to: 'likes#create_like', as: 'add_like'
    post '/postagens/:post_id/dislike', to: 'likes#create_dislike', as: 'add_dislike'
  end
end

app/models/board_goal.rb
class BoardGoal < ApplicationRecord
  belongs_to :board

  has_many :board_goal_tasks

  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :board, presence: true
end

app/controllers/board_goals_controller.rb
class BoardGoalsController < ApplicationController
  before_action :set_board_goal, only: [:show, :edit, :update, :destroy]
  before_action :set_board, only: [:edit]

  # GET /board_goals
  # GET /board_goals.json
  def index
    @board_goals = BoardGoal.all
  end

  # GET /board_goals/1
  # GET /board_goals/1.json
  def show
  end

  # GET /board_goals/new
  def new
    @board_goal = BoardGoal.new
    @board = Board.find_by id: params[:board_id]
  end

  # GET /board_goals/1/edit
  def edit
  end

  # POST /board_goals
  # POST /board_goals.json
  def create
    @board_goal = BoardGoal.new(board_goal_params)
    @board = Board.find_by id: params[:board_id]
    @board_goal.board = @board

    respond_to do |format|
      if @board_goal.save
        format.html { redirect_to @board_goal.board, notice: 'Meta de diretoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @board_goal }
      else
        format.html { render :new }
        format.json { render json: @board_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_goals/1
  # PATCH/PUT /board_goals/1.json
  def update
    respond_to do |format|
      if @board_goal.update(board_goal_params)
        format.html { redirect_to @board_goal.board, notice: 'Meta de diretoria editada com sucesso.' }
        format.json { render :show, status: :ok, location: @board_goal }
      else
        format.html { render :edit }
        format.json { render json: @board_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_goals/1
  # DELETE /board_goals/1.json
  def destroy
    @board_goal.destroy
    respond_to do |format|
      format.html { redirect_to board_goals_url, notice: 'Meta de diretoria excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find_by id: params[:board_id]
      redirect_to boards_path if @board.nil?
    end

    def set_board_goal
      @board_goal = BoardGoal.find_by(board_id: params[:board_id], id: params[:goal_id])
      redirect_to boards_path if @board_goal.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_goal_params
      params.require(:board_goal).permit(:name)
    end
end

app/helpers/board_goals_helper.rb
module BoardGoalsHelper
end

app/views/board_goals/_edit_form.html.erb
<%= form_with model: board_goal, local: true, url: board_goal_path, method: :patch do |form| %>
  <div class="field">
    <%= form.label :name, 'Nova meta: ' %>
    <%= form.text_field :name %>
  </div>

  <%= form.submit 'Concluir edição' %>
<% end %>

app/views/board_goals/_form.html.erb
<%= form_with(model: board_goal, local: true) do |form| %>
  <% if board_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_goal.errors.count, "error") %> prohibited this board_goal from being saved:</h2>

      <ul>
      <% board_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Digite a nova meta' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar meta' %>
  </div>
<% end %>

app/views/board_goals/_new_form.html.erb
<%= form_with(model: board_goal, local: true, url: board_goals_path) do |form| %>
  <% if board_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_goal.errors.count, "erro") %> ao criar meta:</h2>

      <ul>
      <% board_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Digite a nova meta: ' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Criar nova tarefa' %>
  </div>
<% end %>

app/views/board_goals/edit.html.erb
<div class = "cell-edit-body">
    <div class = "cell-edit">
        <%= link_to '', @board_goal.board, class: "fas fa-arrow-left fa-2x"%>
        <%= link_to '', @board_goal, class: "fas fa-external-link-alt fa-2x" %>

        <h2>Editing Board Goal</h2>

        <%= render 'edit_form', board_goal: @board_goal %>
    </div>
</div>

app/views/board_goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Board Goals</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @board_goals.each do |board_goal| %>
      <tr>
        <td><%= board_goal.board %></td>
        <td><%= link_to 'Show', board_goal %></td>
        <td><%= link_to 'Edit', edit_board_goal_path(board_goal) %></td>
        <td><%= link_to 'Destroy', board_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board Goal', new_board_goal_path %>

app/views/board_goals/new.html.erb
<div class = "cell-new-body">
    <div class = "cell-new">
        <%= link_to '', @board, class: "fas fa-arrow-left fa-3x"%>
        <h2 class = "new-cell-title">New Board Goal <%= @board.name %></h2>

        <%= render 'new_form', board_goal: @board_goal %>
    </div>
</div>

app/views/board_goals/show.html.erb
<div class = "project-show-body">
  <div class = "project-show">
    <p id="notice"><%= notice %></p>
    <%= link_to '', edit_board_goal_path(@board_goal.board, @board_goal), class: "far fa-edit fa-2x" %>
    
    <p class = "project-title">
      <strong>Diretoria: </strong>
      <%= @board_goal.board.name %>
    </p>

    <div class = "project-infos">
      <div>
        <strong>Meta: </strong>
        </div>
      <div>
        <%= @board_goal.name %>
        </div>
    </div>


    <div class = "project-infos">
      <div>
        <strong> Status: </strong>
        </div>
      <div>
        <% if @board_goal.done %>
          Concluída
        <% else %>
          Não Concluída
        <% end %>
      </div>
    </div>
 
  </div>
</div>