config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  devise_for :users

  resources :cell_goal_tasks
  resources :cell_goals
  resources :board_goal_tasks
  # resources :board_goals
  resources :projects
  resources :cell_tasks
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :boards
  resources :cells
    


  # Tarefas de uma Diretoria
  get '/boards/:board_id/tasks/new', to: 'board_tasks#new', as: 'new_board_task'
  post '/boards/:board_id/tasks', to: 'board_tasks#create', as: 'board_tasks'
  get '/boards/:board_id/tasks/:task_id', to: 'board_tasks#show', as: 'board_task'
  patch '/boards/:board_id/tasks/:task_id', to: 'board_tasks#update'
  get '/boards/:board_id/tasks/:task_id/edit', to: 'board_tasks#edit', as: 'edit_board_task'

  # Metas de uma diretoria
  get '/boards/:board_id/goals/new', to: 'board_goals#new', as: 'new_board_goal'
  post '/boards/:board_id/goals', to: 'board_goals#create', as: 'board_goals'
  get '/boards/:board_id/goals/:goal_id', to: 'board_goals#show', as: 'board_goal'
  get '/boards/:board_id/goals/:goal_id/edit', to: 'board_goals#edit', as: 'edit_board_goal'
  patch '/boards/:board_id/goals/:goal_id', to: 'board_goals#update'

  namespace :forum do
    get '/', to: 'posts#index'
    get '/postagens', to: 'posts#index', as: 'posts'
    get '/postagens/novo', to: 'posts#new', as: 'new_post'
    post '/postagens', to: 'posts#create'

    get '/postagens/:id', to: 'posts#show', as: 'post'

    delete '/postagens/:id', to: 'posts#destroy'

    post '/postagens/:post_id/like', to: 'likes#create_like', as: 'add_like'
    post '/postagens/:post_id/dislike', to: 'likes#create_dislike', as: 'add_dislike'
  end
end

app/controllers/forum/likes_controller.rb
class Forum::LikesController < ApplicationController
  before_action :prevent_not_logged_user
  before_action :set_forum_post, only: [:create_like, :create_dislike]

  def create_like
    user_reaction = Like.where(user: current_user, forum_post: @forum_post).first

    if user_reaction.nil?
      new_reaction = Like.new user: current_user, forum_post: @forum_post, kind: Like.kinds[:positive]
      new_reaction.save
    elsif user_reaction.positive?
      user_reaction.destroy
    elsif user_reaction.negative?
      user_reaction.destroy
      new_reaction = Like.new user: current_user, forum_post: @forum_post, kind: Like.kinds[:positive]
      new_reaction.save
    end

    redirect_to @forum_post
  end

  def create_dislike
    user_reaction = Like.where(user: current_user, forum_post: @forum_post).first

    if user_reaction.nil?
      new_reaction = Like.new user: current_user, forum_post: @forum_post, kind: Like.kinds[:negative]
      new_reaction.save
    elsif user_reaction.negative?
      user_reaction.destroy
    elsif user_reaction.positive?
      user_reaction.destroy
      new_reaction = Like.new user: current_user, forum_post: @forum_post, kind: Like.kinds[:negative]
      new_reaction.save
    end

    redirect_to @forum_post
  end

  private

    def set_forum_post
      @forum_post = ForumPost.find_by id: params[:post_id]
    end

    def prevent_not_logged_user
      redirect_to new_user_session_path if current_user.nil?
    end
end

app/controllers/forum/posts_controller.rb
class Forum::PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  before_action :prevent_not_logged_user

  def index
    @posts = ForumPost.all
  end

  def new
    @post = ForumPost.new
  end

  def show
    redirect_to forum_posts_path if @post.nil?
  end

  def create
    @post = ForumPost.new(forum_post_params)
    @post.user = current_user
    if @post.save
      redirect_to forum_posts_path
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to forum_posts_path
  end

  private

    def set_post
      @post = ForumPost.find_by id: params[:id]
    end

    def forum_post_params
      params.require(:forum_post).permit(:title, :content)
    end
end

app/helpers/forum/likes_helper.rb
module Forum::LikesHelper
end

app/helpers/forum/posts_helper.rb
module Forum::PostsHelper
end

app/views/forum/posts/_form.html.erb
<div class = "forum-form-new-post">
  <%= form_with model: forum_post, local: true do |form| %>
    <% if forum_post.errors.any? %>
      <div class="errors">
        <ul>
          <% forum_post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label :title %></br>
      <%= form.text_field :title, required: true %></br>
    </div>

    <div class="field forum-field-content">
      <%= form.label :content %></br>
      <%= form.text_area :content, placeholder: "Digite sua postagem aqui..." , required: true %>
    </div>

    <%= form.submit %>
  <% end %>
</div>

app/views/forum/posts/index.html.erb
<div class = "forum-index">

<div class = "h1-and-button">
      <div>
        <h1>Navegue pelos posts do fórum</h1>
      </div>
      <div>
        <%= link_to '<button type="button">Novo Post</button>'.html_safe, forum_new_post_path, method: :get %>
      </div>
    </div>

  <div class = "forum-index-posts">
    <% @posts.each do |post| %>
      <div class="post">
        <h3> <%= link_to post.title, post %> </h3>
        <p> Postado por: <%= link_to post.user.full_name, post.user %> </p>
      </div>
    <% end %>
  </div>

  
</div>

app/views/forum/posts/new.html.erb
<div class = "forum-new-post">
    <h2> Novo Post </h2>

    <%= render 'form', forum_post: @post %>
</div>

app/views/forum/posts/show.html.erb
<div class = "forum-post-body">
  <div class = "forum-post">
    <h2> <%= @post.title %> </h2>

    <div class="content">
      <div class="post_text">
        <p> <%= @post.content %> </p>
      </div>
      <p> Postado por: <%= link_to @post.user.full_name, @post.user %> </p>
     
    </div>
    <div class = "forum-links">
      <div class="like">
        <%= button_to '', forum_add_like_path(@post) %>             
        <p> <%= @post.number_of_likes %>  </p>
      </div> 
      <div class="dislike">
        <%= button_to '', forum_add_dislike_path(@post) %>  
        <p> <%= @post.number_of_dislikes %>  </p>      
      </div>
      <%= link_to 'Voltar', forum_posts_path %>
      <%= link_to 'Excluir', forum_post_path, method: :delete %>              
    </div>
  </div>
</div>