config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  devise_for :users

  resources :cell_goal_tasks
  resources :cell_goals
  resources :board_goal_tasks
  # resources :board_goals
  resources :projects
  resources :cell_tasks
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :boards
  resources :cells
    


  # Tarefas de uma Diretoria
  get '/boards/:board_id/tasks/new', to: 'board_tasks#new', as: 'new_board_task'
  post '/boards/:board_id/tasks', to: 'board_tasks#create', as: 'board_tasks'
  get '/boards/:board_id/tasks/:task_id', to: 'board_tasks#show', as: 'board_task'
  patch '/boards/:board_id/tasks/:task_id', to: 'board_tasks#update'
  get '/boards/:board_id/tasks/:task_id/edit', to: 'board_tasks#edit', as: 'edit_board_task'

  # Metas de uma diretoria
  get '/boards/:board_id/goals/new', to: 'board_goals#new', as: 'new_board_goal'
  post '/boards/:board_id/goals', to: 'board_goals#create', as: 'board_goals'
  get '/boards/:board_id/goals/:goal_id', to: 'board_goals#show', as: 'board_goal'
  get '/boards/:board_id/goals/:goal_id/edit', to: 'board_goals#edit', as: 'edit_board_goal'
  patch '/boards/:board_id/goals/:goal_id', to: 'board_goals#update'

  namespace :forum do
    get '/', to: 'posts#index'
    get '/postagens', to: 'posts#index', as: 'posts'
    get '/postagens/novo', to: 'posts#new', as: 'new_post'
    post '/postagens', to: 'posts#create'

    get '/postagens/:id', to: 'posts#show', as: 'post'

    delete '/postagens/:id', to: 'posts#destroy'

    post '/postagens/:post_id/like', to: 'likes#create_like', as: 'add_like'
    post '/postagens/:post_id/dislike', to: 'likes#create_dislike', as: 'add_dislike'
  end
end

app/models/cell_goal.rb
class CellGoal < ApplicationRecord
  belongs_to :cell
  has_many :cell_goal_tasks, dependent: :destroy
end

app/controllers/cell_goals_controller.rb
class CellGoalsController < ApplicationController
  before_action :set_cell_goal, only: [:show, :edit, :update, :destroy]

  # GET /cell_goals
  # GET /cell_goals.json
  def index
    @cell_goals = CellGoal.all
  end

  # GET /cell_goals/1
  # GET /cell_goals/1.json
  def show
  end

  # GET /cell_goals/new
  def new
    @cell_goal = CellGoal.new
  end

  # GET /cell_goals/1/edit
  def edit
  end

  # POST /cell_goals
  # POST /cell_goals.json
  def create
    @cell_goal = CellGoal.new(cell_goal_params)

    respond_to do |format|
      if @cell_goal.save
        format.html { redirect_to @cell_goal, notice: 'Cell goal was successfully created.' }
        format.json { render :show, status: :created, location: @cell_goal }
      else
        format.html { render :new }
        format.json { render json: @cell_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cell_goals/1
  # PATCH/PUT /cell_goals/1.json
  def update
    respond_to do |format|
      if @cell_goal.update(cell_goal_params)
        format.html { redirect_to @cell_goal, notice: 'Cell goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell_goal }
      else
        format.html { render :edit }
        format.json { render json: @cell_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cell_goals/1
  # DELETE /cell_goals/1.json
  def destroy
    @cell_goal.destroy
    respond_to do |format|
      format.html { redirect_to cell_goals_url, notice: 'Cell goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell_goal
      @cell_goal = CellGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_goal_params
      params.require(:cell_goal).permit(:cell_id, :goal_name)
    end
end

app/helpers/cell_goals_helper.rb
module CellGoalsHelper
end

app/views/cell_goals/_form.html.erb
<%= form_with(model: cell_goal, local: true) do |form| %>
  <% if cell_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell_goal.errors.count, "error") %> prohibited this cell_goal from being saved:</h2>

      <ul>
      <% cell_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form"> 
  <div class="field">
    <%= form.hidden_field :cell_id, value: params[:cell_id] %>
  </div>

  <div class="field">
    <%= form.label :goal_name%>
    <%= form.text_field :goal_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/cell_goals/edit.html.erb
<div class = "cell-edit-body">
    <div class = "cell-edit">
        <%= link_to '', cell_goals_path, class: "fas fa-arrow-left fa-2x"%>
        <%= link_to '', @cell_goal, class: "fas fa-external-link-alt fa-2x" %>
        <h2>Editing Cell Goal</h2>

        <%= render 'form', cell_goal: @cell_goal %>

    </div>
</div>

app/views/cell_goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cell Goals</h1>

<table>
  <thead>
    <tr>
      <th>Cell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cell_goals.each do |cell_goal| %>
      <tr>
        <td><%= cell_goal.cell.name %></td>
        <td><%= cell_goal.goal_name %></td>
        <td><%= link_to 'Show', cell_goal %></td>
        <td><%= link_to 'Edit', edit_cell_goal_path(cell_goal) %></td>
        <td><%= link_to 'Destroy', cell_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/cell_goals/new.html.erb
<div class = "cell-new-body">
    <div class = "cell-new">
        <%= link_to '', cells_path, class: "fas fa-arrow-left fa-3x"%>
        <h2 class = "new-cell-title">New Cell Goal</h2>
        <%= render 'form', cell_goal: @cell_goal %>
    </div>
</div>

app/views/cell_goals/show.html.erb
<div class = "project-show-body">
  <%= link_to '<button type="button">New Cell Goal</button>'.html_safe, new_cell_goal_path %>
  <div class = "project-show">
    <%= link_to '', cell_path(@cell_goal.cell_id), class: "fas fa-arrow-left fa-2x" %>
    <%= link_to '', edit_cell_goal_path(@cell_goal), class: "far fa-edit fa-2x" %>
    
    


    <div class = "project-infos">
      <div>
        <strong>Name:</strong>
      </div>
      <div>
        <%= @cell_goal.goal_name %>
      </div>
    </div>

    <div class = "project-infos">
      <div>
        <strong>Cell:</strong>
      </div>
      <div>
        <%= @cell_goal.cell.name %>
      </div>
    </div>

    <div class = "project-infos">
      <strong>Tarefas:</strong>
      <%= link_to '', new_cell_goal_task_path(cell_goal_id: @cell_goal.id), class: "fas fa-plus-circle fa-lg" %>
      <div class = "cell-goal-task">
        <ul>
          <% @cell_goal.cell_goal_tasks.each do |cell_goal_task| %>
            <li class = "board-text"><%= cell_goal_task.task_name %></li>
        <% end %>
        </ul>
       </div> 
    </div>

  </div>
</div>