config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  devise_for :users

  resources :cell_goal_tasks
  resources :cell_goals
  resources :board_goal_tasks
  # resources :board_goals
  resources :projects
  resources :cell_tasks
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :boards
  resources :cells
    


  # Tarefas de uma Diretoria
  get '/boards/:board_id/tasks/new', to: 'board_tasks#new', as: 'new_board_task'
  post '/boards/:board_id/tasks', to: 'board_tasks#create', as: 'board_tasks'
  get '/boards/:board_id/tasks/:task_id', to: 'board_tasks#show', as: 'board_task'
  patch '/boards/:board_id/tasks/:task_id', to: 'board_tasks#update'
  get '/boards/:board_id/tasks/:task_id/edit', to: 'board_tasks#edit', as: 'edit_board_task'

  # Metas de uma diretoria
  get '/boards/:board_id/goals/new', to: 'board_goals#new', as: 'new_board_goal'
  post '/boards/:board_id/goals', to: 'board_goals#create', as: 'board_goals'
  get '/boards/:board_id/goals/:goal_id', to: 'board_goals#show', as: 'board_goal'
  get '/boards/:board_id/goals/:goal_id/edit', to: 'board_goals#edit', as: 'edit_board_goal'
  patch '/boards/:board_id/goals/:goal_id', to: 'board_goals#update'

  namespace :forum do
    get '/', to: 'posts#index'
    get '/postagens', to: 'posts#index', as: 'posts'
    get '/postagens/novo', to: 'posts#new', as: 'new_post'
    post '/postagens', to: 'posts#create'

    get '/postagens/:id', to: 'posts#show', as: 'post'

    delete '/postagens/:id', to: 'posts#destroy'

    post '/postagens/:post_id/like', to: 'likes#create_like', as: 'add_like'
    post '/postagens/:post_id/dislike', to: 'likes#create_dislike', as: 'add_dislike'
  end
end

app/models/cell.rb
class Cell < ApplicationRecord
  has_many :joins
  has_many :members, through: :joins, source: :user
  belongs_to :board

  validates :name, presence: true, uniqueness: true
  validates :board, presence: true

  has_many :cell_tasks, dependent: :destroy
  has_many :cell_goals, dependent: :destroy
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: [:show, :edit, :update, :destroy]
  before_action :prevent_not_logged_user

  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all
  end

  # GET /cells/1
  # GET /cells/1.json
  def show
    if @cell.nil?
      redirect_to cells_path
      return
    end

    @cell_join = Join.all

    @cell_manager = User.find_by(kind: 'manager', joins: @cell.id)

    @cell_tasks = CellTask.where({cell_id: @cell.id})
    #@cell_tasks = CellTask.where("id = #{@cell.id}")
    
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  # GET /cells/1/edit
  def edit
    @cell = Cell.find(params[:id])
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell was successfully created.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Cell was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Cell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find_by(id: params[:id])
    end

    # def survey_params
    #   params.require(:survey).permit(:name,
    #     :questions_attributes => [:id, :content,
    #       :answers_attributes => [:id, :content, :participant_id]
    #     ])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:name, :board_id)
    end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/views/cells/_form.html.erb
<%= form_with(model: cell, local: true) do |form| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form"> 
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :board_id %>
    <%= form.collection_select :board_id, Board.all, :id, :name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/cells/edit.html.erb
<div class = "cell-edit-body">
    <div class = "cell-edit">
        <%= link_to '', cells_path, class: "fas fa-arrow-left fa-2x"%>
        <%= link_to '', @cell, class: "fas fa-external-link-alt fa-2x" %>

        <h2>Editing Cell</h2>

        <%= render 'form', cell: @cell %>
    </div>
</div>

app/views/cells/index.html.erb
<div class = "cells-index">
  <p id="notice"><%= notice %></p>

  <div class = "h1-and-button">
      <div>
        <h1>Cells</h1>
      </div>
      <div>
        <%= link_to '<button type="button">New Cell</button>'.html_safe, new_cell_path %>
      </div>
  </div>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Board</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cells.each do |cell| %>
        <tr>
          <td><%= cell.name %></td>
          <td><%= cell.board.name %></td>
          <td><%= link_to '', cell, class: "fas fa-external-link-alt fa-lg" %></td>
          <td><%= link_to '', edit_cell_path(cell), class: "far fa-edit fa-lg" %></td>
          <td><%= link_to '', cell, class: "fas fa-trash-alt fa-lg", method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/cells/new.html.erb
<div class = "cell-new-body">
    <div class = "cell-new">
        <%= link_to '', cells_path, class: "fas fa-arrow-left fa-3x"%>
        <h2 class = "new-cell-title">New Cell</h2>

        <%= render 'form', cell: @cell %>
    </div>
</div>

app/views/cells/show.html.erb
<div class = "cell-show-body">
  <div class = "cell-show">
    <p id="notice"><%= notice %></p>
    <%= link_to '', edit_cell_path(@cell), class: "far fa-edit fa-2x" %>


    <p class = "cell-title">
      <%= @cell.name %>
    </p>

    <div class = "cell-infos">
      <div>
        <strong>Gerente<strong>
      </div>
      <div>
        <%= @cell_manager %>
      </div>
    </div>

    <div class = "cell-infos">
      <div>
        <%= @cell.board.name %>
      </div>
    </div>

    <div class = "cell-infos">
      <div> 
        <strong>Membros<strong>
      </div>
      <div>
        <% @cell_join.each do |cell_join| %>
          <%= cell_join.user.first_name %><br/>
        <% end %>
      </div>
    </div>



    </div>

    <div class = "board-tasks">
      <div class="container_board">  

        <div class = "board">
          <%= link_to '', new_cell_task_path(cell_id: @cell.id) , class: "fas fa-plus-circle fa-2x" %>
          <h2 class = "tasks-and-goals">Tarefas</h2><br>
          
          <ul>
            <% @cell_tasks.each do |cell_task| %>
              <div class = "task-name">
                <li class = "board-text"><%= cell_task.name %></li>
                <%= link_to '', edit_cell_task_path(cell_task), class: "far fa-edit fa-lg"%><br>
              </div>
            <% end %>
          </ul>
        </div>

        <div class = "board">
          <%= link_to '', new_cell_goal_path(cell_id: @cell.id), class: "fas fa-plus-circle fa-2x" %>
          <h2 class = "tasks-and-goals">Metas</h2><br>
          
          <ul>
            <% @cell.cell_goals.each do |cell_goal| %>
              <div class = "task-name">
                <li class = "board-text"><%= link_to cell_goal.goal_name, cell_goal %></li>
              </div>
            <% end %>
          </ul>
        </div>

      </div>

  </div>